=== SlenderData/XML-Learning/Chapter 4/demo-3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.org/IPO"
           xmlns:ipo="http://www.example.org/IPO"
           elementFormDefault="qualified">

    <xs:element name="PURCHASEORDER" type="ipo:PurchaseOrderType"/>

    <xs:complexType name="PurchaseOrderType">
        <xs:sequence>
            <xs:element name="ORDER" type="ipo:OrderType"/>
        </xs:sequence>
        <xs:attribute name="PRODID" type="xs:string" use="required"/>
        <xs:attribute name="ORDERID" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="OrderType">
        <xs:sequence>
            <xs:element name="DATE" type="xs:date"/>
            <xs:element name="PRODUCTNAME" type="xs:string"/>
            <xs:element name="SUPPLIERNAME" type="xs:string"/>
            <xs:element name="ADDRESS" type="xs:string"/>
            <xs:element name="QUANTITY" type="xs:integer"/>
            <xs:element name="PRICEPERQTY" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== SlenderData/XML-Learning/Chapter 4/demo-3.xml
<?xml version="1.0"?>
<ipo:PURCHASEORDER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns:ipo="http://www.example.org/IPO"
                   xsi:schemaLocation="http://www.example.org/IPO demo-3.xsd"
                   PRODID="P001" ORDERID="O001">
    <ORDER>
        <DATE>2000-02-13</DATE>
        <PRODUCTNAME>BARBIE DOLL</PRODUCTNAME>
        <SUPPLIERNAME>MIKE</SUPPLIERNAME>
        <ADDRESS>15, LITION STREET</ADDRESS>
        <QUANTITY>3</QUANTITY>
        <PRICEPERQTY>200</PRICEPERQTY>
    </ORDER>
</ipo:PURCHASEORDER>
